markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "潘学文"
email: winfirm#163.com
name: "潘学文个人博客"
url: http://www.panxw.com
domain: www.panxw.com
all_categories: [
["read", "读书笔记","/posts/read.html"], 
["about", "关于","/about.html"]
]

paginate: 3
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
