markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

author: "Haoyuan Zhang"
email: haoyuan.zhang@qmul.ac.uk
name: "Haoyuan Zhang"
url: haoyuanzhang1990.github.io
all_categories: [
["read", "Research","/posts/read.html"], 
["about", "About","/about.html"]
]

paginate: 3
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
